dist: xenial

language: go
go:
  - "1.x.x"

# Install the dependencies.
install:
  - go get -t -v ./...

notifications:
  email: false

# Install GnuPG.
before_install:
  - sudo apt-get update
  - sudo apt-get install -y gpgv2

# Start the gpg-agent in the background before running the test suite.
before_script:
  - gpg-agent --homedir testdata/gnupg --daemon

script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - test -z $(gofmt -s -l $GO_FILES)
  - go test -v -race ./...
